version: '3.8'

services:
  postgres:
    image: postgres:17.4
    container_name: fleet-manager-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql@17.4/data
      - ./postgresql-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fleet-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: fleet-manager-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - fleet-network

  kafka:
    image: confluentinc/cp-kafka:7.9.0
    container_name: fleet-manager-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - fleet-network
    volumes:
      - ./kafka:/home/appuser
    post_start:
      - command: ["sh", "-c", "/home/appuser/create-topics.sh"]

volumes:
  postgres-data:

networks:
  fleet-network:
    driver: bridge
