version: '3.8'

services:
  # Quarkus Application
#  fleet-api:
#    build:
#      context: ./fleet-api
#      dockerfile: src/main/docker/Dockerfile.jvm
#    container_name: fleet-management-api
#    ports:
#      - "8080:8080"
#    environment:
#      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
#      - QUARKUS_DATASOURCE_USERNAME=postgres_username
#      - QUARKUS_DATASOURCE_PASSWORD=postgres_password
#    depends_on:
#      postgres:
#        condition: service_healthy
#    networks:
#      - fleet-network

  # PostgreSQL Database
  postgres:
    image: postgres:17.4
    container_name: fleet-manager-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fleet_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql@17.4/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fleet-network

volumes:
  postgres-data:

networks:
  fleet-network:
    driver: bridge
